[package]
name = "pheasant_macro_get"
version = "0.1.1"
edition = "2024"

[lib]
proc-macro = true

[[test]]
name = "basic"
path = "tests/basic.rs"

[[test]]
name = "mime"
path = "tests/mime.rs"

[[test]]
name = "re"
path = "tests/re.rs"

[[bin]]
path = "src/main.rs"
name = "dev"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["extra-traits", "full", "parsing"] }
chrono = { version = "0.4.41", features = ["serde"] }
serde_json = "1.0.142"
pheasant_core = { version = "0.1.0", path = "../pheasant_core" }
pheasant_uri = { version = "0.1.0", path = "../pheasant_uri" }
pheasant_macro_utils = { version = "0.1.0", path = "../pheasant_macro_utils" }
