[package]
name = "pheasant_macro_get"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[[test]]
name = "ss"
path = "tests/syntax_semantics.rs"

[[bin]]
path = "src/main.rs"
name = "dev"

[dependencies]
impls = "1.0.3"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.104", features = ["extra-traits", "full", "parsing"] }
